name: snowball_sdk_firebase
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  firebase_analytics: ^11.4.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_messaging: ^15.2.0
  firebase_remote_config: ^5.3.0
  logger: ^2.5.0
  device_info_plus: ^11.2.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.snowball.snowball_sdk_firebase
        pluginClass: SnowballSdkFirebasePlugin
      ios:
        pluginClass: SnowballSdkFirebasePlugin
